### ISSUE TITLE
Kind property of function app service in ARM template Function.json is wrong.

### ISSUE THREAD

**Issue by ckadluba** [samsmithnz/DevOpsMetrics#500]
The kind property in Templates/Function.json is set to `app` which creates a app type instead of a function app service when executing `DeployInfrastructureToAzure.ps1`.

```json
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "apiVersion": "2018-11-01",
      "name": "[parameters('webSiteName')]",
      "location": "[resourceGroup().location]",
      "dependsOn": [
      ],
      "kind": "app",
      "tags": {
        "displayName": "Function"
      },
```

it has to be changed to `functionapp` so the app can be deployed.

**Comment by samsmithnz** [comment]
Sorry for the delay in responding @ckadluba. Thanks for the update - running the CI/CD now.
